/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShadButton {
    }
}
declare global {
    interface HTMLShadButtonElement extends Components.ShadButton, HTMLStencilElement {
    }
    var HTMLShadButtonElement: {
        prototype: HTMLShadButtonElement;
        new (): HTMLShadButtonElement;
    };
    interface HTMLElementTagNameMap {
        "shad-button": HTMLShadButtonElement;
    }
}
declare namespace LocalJSX {
    interface ShadButton {
    }
    interface IntrinsicElements {
        "shad-button": ShadButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shad-button": LocalJSX.ShadButton & JSXBase.HTMLAttributes<HTMLShadButtonElement>;
        }
    }
}
