/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShadButton {
        "asChild": boolean;
        "disabled": boolean;
        "icon"?: string;
        "loading": boolean;
        "loadingText": string;
        "size": 'small' | 'medium' | 'large';
        "variant": 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
    }
}
declare global {
    interface HTMLShadButtonElement extends Components.ShadButton, HTMLStencilElement {
    }
    var HTMLShadButtonElement: {
        prototype: HTMLShadButtonElement;
        new (): HTMLShadButtonElement;
    };
    interface HTMLElementTagNameMap {
        "shad-button": HTMLShadButtonElement;
    }
}
declare namespace LocalJSX {
    interface ShadButton {
        "asChild"?: boolean;
        "disabled"?: boolean;
        "icon"?: string;
        "loading"?: boolean;
        "loadingText"?: string;
        "size"?: 'small' | 'medium' | 'large';
        "variant"?: 'primary' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
    }
    interface IntrinsicElements {
        "shad-button": ShadButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shad-button": LocalJSX.ShadButton & JSXBase.HTMLAttributes<HTMLShadButtonElement>;
        }
    }
}
